USE careerforge_db;

-- Update mock_tests to add category column if missing
-- ALTER TABLE mock_tests ADD COLUMN IF NOT EXISTS category VARCHAR(50) DEFAULT 'COMPETITIVE';

-- Delete old sparse tests and replace with full 30-question sets
DELETE FROM mock_tests WHERE title IN ('Aptitude Assessment - Quant & Logical','Core Java & Database Quiz');

-- ============================================================
-- 1. COMPETITIVE - Quantitative Aptitude (30 Questions)
-- ============================================================
INSERT INTO mock_tests (title, type, duration_minutes, category, questions) VALUES 
('Competitive Aptitude Test - Full (30Q)', 'APTITUDE', 40, 'COMPETITIVE',
'[
{"id":1,"question":"A train 150m long passes a pole in 15 seconds. Its speed is?","options":["10 m/s","36 km/h","7.5 m/s","Both A and B"],"answer":"Both A and B","explanation":"Speed = 150/15 = 10 m/s = 36 km/h"},
{"id":2,"question":"If A:B = 2:3 and B:C = 4:5, then A:B:C is?","options":["8:12:15","6:9:10","2:3:5","4:6:8"],"answer":"8:12:15","explanation":"A:B=2:3=8:12, B:C=4:5=12:15, so A:B:C=8:12:15"},
{"id":3,"question":"A shopkeeper sells at 20% profit. If CP=500, what is SP?","options":["600","550","520","580"],"answer":"600","explanation":"SP = CP × 1.2 = 500 × 1.2 = 600"},
{"id":4,"question":"Find the LCM of 12, 18, and 24.","options":["36","72","48","96"],"answer":"72","explanation":"LCM(12,18,24) = 72"},
{"id":5,"question":"The HCF of 36 and 48 is?","options":["6","12","18","24"],"answer":"12","explanation":"36=4×9=2²×3², 48=16×3=2⁴×3, HCF=2²×3=12"},
{"id":6,"question":"2/5 of a number is 40. What is 75% of the number?","options":["60","75","80","90"],"answer":"75","explanation":"Number=100, 75% of 100=75"},
{"id":7,"question":"Simple interest on Rs 8000 at 5% for 3 years is?","options":["1200","1600","2000","800"],"answer":"1200","explanation":"SI = (8000×5×3)/100 = 1200"},
{"id":8,"question":"If CODE is written as DPEF, then MANGO is written as?","options":["NBMHP","NBNHP","NANHP","NAOHQ"],"answer":"NBNHP","explanation":"Each letter is shifted by +1"},
{"id":9,"question":"A can do work in 10 days, B in 15 days. Together they finish in?","options":["6 days","8 days","5 days","12 days"],"answer":"6 days","explanation":"1/10+1/15=5/30=1/6, so 6 days"},
{"id":10,"question":"What percent of 80 is 20?","options":["25%","20%","15%","30%"],"answer":"25%","explanation":"(20/80)×100=25%"},
{"id":11,"question":"The ratio of boys to girls is 3:2. If there are 30 boys, how many girls?","options":["20","25","15","18"],"answer":"20","explanation":"Girls = 30×(2/3) = 20"},
{"id":12,"question":"A number increased by 30% becomes 91. What is the original?","options":["70","65","80","75"],"answer":"70","explanation":"x×1.3=91, x=70"},
{"id":13,"question":"Speed of boat in still water is 8 km/h, stream speed is 2 km/h. Downstream speed?","options":["10 km/h","6 km/h","4 km/h","12 km/h"],"answer":"10 km/h","explanation":"Downstream = 8+2 = 10 km/h"},
{"id":14,"question":"Average of 5 numbers is 40. If one number is removed, average becomes 35. Removed number?","options":["60","55","65","70"],"answer":"60","explanation":"Sum=200, new sum=140, removed=200-140=60"},
{"id":15,"question":"In how many ways can 5 people be arranged in a line?","options":["120","60","24","20"],"answer":"120","explanation":"5! = 120"},
{"id":16,"question":"Compound interest on Rs 10000 at 10% for 2 years (compounded annually)?","options":["2100","2000","1900","2500"],"answer":"2100","explanation":"CI = 10000×(1.1²-1) = 2100"},
{"id":17,"question":"If 6 men or 10 women can do work in 20 days, 3 men and 5 women finish in?","options":["20 days","15 days","10 days","25 days"],"answer":"20 days","explanation":"3 men+5 women = 6 men equivalent, same rate, same time = 20 days"},
{"id":18,"question":"Find the next number: 2, 6, 12, 20, 30, ?","options":["42","38","44","40"],"answer":"42","explanation":"Differences: 4,6,8,10,12 → next = 30+12=42"},
{"id":19,"question":"The perimeter of a square is 48. Its area is?","options":["144","96","120","108"],"answer":"144","explanation":"Side=12, Area=12²=144"},
{"id":20,"question":"A clock shows 3:00. What is the angle between the hands?","options":["90°","60°","120°","45°"],"answer":"90°","explanation":"At 3:00, hands are at 90° angle"},
{"id":21,"question":"If 40% of X = 60% of Y, then X:Y is?","options":["3:2","2:3","4:3","3:4"],"answer":"3:2","explanation":"0.4X=0.6Y → X/Y = 0.6/0.4 = 3/2"},
{"id":22,"question":"In a class of 50, 30 passed Math, 25 passed Science, 10 passed both. How many failed both?","options":["5","10","15","20"],"answer":"5","explanation":"Passed at least one = 30+25-10=45, Failed both = 50-45=5"},
{"id":23,"question":"What is the probability of getting a head when a fair coin is tossed?","options":["1/2","1/4","1/3","2/3"],"answer":"1/2","explanation":"P(Head) = 1/2 for a fair coin"},
{"id":24,"question":"Find the missing term: 3, 9, 27, ?, 243","options":["81","54","72","63"],"answer":"81","explanation":"Each term is multiplied by 3, so 27×3=81"},
{"id":25,"question":"A discount of 10% followed by 20% discount is equivalent to a total discount of?","options":["28%","30%","25%","27%"],"answer":"28%","explanation":"Effective = 1-(0.9×0.8) = 1-0.72 = 28%"},
{"id":26,"question":"Ramesh is 15th from left and 12th from right. Total students in row?","options":["26","27","28","25"],"answer":"26","explanation":"Total = 15+12-1 = 26"},
{"id":27,"question":"Sum of first 20 natural numbers is?","options":["210","200","190","220"],"answer":"210","explanation":"Sum = n(n+1)/2 = 20×21/2 = 210"},
{"id":28,"question":"The area of a circle with radius 7 cm is? (π=22/7)","options":["154 cm²","144 cm²","164 cm²","174 cm²"],"answer":"154 cm²","explanation":"Area = π×r² = (22/7)×49 = 154"},
{"id":29,"question":"A and B invest Rs 5000 and Rs 3000. Profit is Rs 4000. A gets?","options":["2500","1500","2000","3000"],"answer":"2500","explanation":"A:B = 5:3, A gets = (5/8)×4000 = 2500"},
{"id":30,"question":"If today is Monday, what day will it be after 100 days?","options":["Wednesday","Tuesday","Thursday","Friday"],"answer":"Wednesday","explanation":"100 mod 7 = 2, Monday+2 = Wednesday"}
]');

-- ============================================================
-- 2. INTERVIEW PREP - HR + Technical Mix (30 Questions)
-- ============================================================
INSERT INTO mock_tests (title, type, duration_minutes, category, questions) VALUES 
('Interview Preparation - Full (30Q)', 'INTERVIEW', 45, 'INTERVIEW',
'[
{"id":1,"question":"Tell me about yourself. What is the best opening line?","options":["Start with personal life","Start with name, education, skills, and career goals","Start with salary expectations","Start with weaknesses"],"answer":"Start with name, education, skills, and career goals","explanation":"A good self-intro covers name, education, key skills, and career objective concisely."},
{"id":2,"question":"What is polymorphism in Java?","options":["Same method name, different implementations","Using multiple classes","Encrypting data","Hiding variables"],"answer":"Same method name, different implementations","explanation":"Polymorphism means one interface, many implementations - via method overloading and overriding."},
{"id":3,"question":"What is the difference between ArrayList and LinkedList?","options":["No difference","ArrayList uses dynamic array, LinkedList uses doubly linked nodes","ArrayList is faster for insertion","LinkedList uses less memory"],"answer":"ArrayList uses dynamic array, LinkedList uses doubly linked nodes","explanation":"ArrayList has O(1) random access but O(n) insertion. LinkedList has O(1) insertion but O(n) access."},
{"id":4,"question":"What is your greatest weakness?","options":["Say you have none","Name a real weakness but show steps you take to improve","Say you work too hard","Mention your colleague flaws"],"answer":"Name a real weakness but show steps you take to improve","explanation":"Honesty + improvement plan shows self-awareness and growth mindset."},
{"id":5,"question":"What is the difference between == and .equals() in Java?","options":["They are identical","== compares references, .equals() compares content","== compares content","equals() only works for numbers"],"answer":"== compares references, .equals() compares content","explanation":"== checks memory address equality; .equals() checks logical equality of object values."},
{"id":6,"question":"What is a deadlock in OS?","options":["System crash","Circular wait where processes hold resources and wait for each other indefinitely","Memory leak","CPU overload"],"answer":"Circular wait where processes hold resources and wait for each other indefinitely","explanation":"Deadlock requires: Mutual Exclusion, Hold & Wait, No Preemption, and Circular Wait."},
{"id":7,"question":"Where do you see yourself in 5 years?","options":["Managing the company","Growing with the company in a senior technical role","Starting a competing firm","Not sure"],"answer":"Growing with the company in a senior technical role","explanation":"Shows ambition aligned with company growth. Avoid overreaching or vague answers."},
{"id":8,"question":"What is normalization in DBMS?","options":["Encrypting data","Process of organizing data to reduce redundancy and improve integrity","Compressing data","Indexing tables"],"answer":"Process of organizing data to reduce redundancy and improve integrity","explanation":"Normalization forms: 1NF (atomic values), 2NF (no partial dependency), 3NF (no transitive dependency)."},
{"id":9,"question":"What is the difference between HTTP and HTTPS?","options":["Same protocol","HTTPS uses SSL/TLS encryption for secure communication","HTTP is faster always","HTTPS is only for banking sites"],"answer":"HTTPS uses SSL/TLS encryption for secure communication","explanation":"HTTPS encrypts data in transit using TLS, preventing eavesdropping and man-in-the-middle attacks."},
{"id":10,"question":"How do you handle stress and pressure?","options":["Avoid stressful situations","Prioritize tasks, break problems into steps, and maintain focus on solutions","Ignore the stress","Ask manager to reduce workload"],"answer":"Prioritize tasks, break problems into steps, and maintain focus on solutions","explanation":"Employers want systematic problem-solvers who stay productive under pressure."},
{"id":11,"question":"What is an interface in Java?","options":["A class with methods","A contract with abstract methods that implementing classes must define","A final class","A runtime exception"],"answer":"A contract with abstract methods that implementing classes must define","explanation":"Interfaces enable multiple inheritance of type in Java and define behavior contracts."},
{"id":12,"question":"What is the difference between process and thread?","options":["Same thing","Process is heavy with own memory; thread is lightweight, sharing memory","Thread uses more memory","Process is faster"],"answer":"Process is heavy with own memory; thread is lightweight, sharing memory","explanation":"Threads within the same process share heap/code but have their own stack and registers."},
{"id":13,"question":"Why should we hire you?","options":["Because I need a job","My skills, passion, and ability to contribute to company goals align perfectly with this role","I have a good GPA","I know the interviewer"],"answer":"My skills, passion, and ability to contribute to company goals align perfectly with this role","explanation":"Highlight specific skills matching the JD and demonstrate genuine interest in the company."},
{"id":14,"question":"What is a REST API?","options":["A database type","An architectural style for networked applications using HTTP methods","A programming language","A design pattern"],"answer":"An architectural style for networked applications using HTTP methods","explanation":"REST uses GET, POST, PUT, DELETE. It is stateless, scalable, and resource-oriented."},
{"id":15,"question":"What is the time complexity of binary search?","options":["O(n)","O(log n)","O(n log n)","O(1)"],"answer":"O(log n)","explanation":"Binary search halves the search space each step, giving O(log n) complexity."},
{"id":16,"question":"What are your strengths?","options":["Say you have no weaknesses","Mention relevant technical and soft skills with concrete examples","List generic terms","Say everything is a strength"],"answer":"Mention relevant technical and soft skills with concrete examples","explanation":"Use STAR method: back each strength with a specific situation and result."},
{"id":17,"question":"What is a foreign key?","options":["A key that is encrypted","A column that references the primary key of another table","A unique key","A backup key"],"answer":"A column that references the primary key of another table","explanation":"Foreign keys enforce referential integrity between related tables."},
{"id":18,"question":"What is exception handling in Java?","options":["Deleting exceptions","Mechanism to handle runtime errors using try-catch-finally","Ignoring errors","Logging errors only"],"answer":"Mechanism to handle runtime errors using try-catch-finally","explanation":"try contains risky code, catch handles specific exceptions, finally always executes."},
{"id":19,"question":"Tell me about a challenge you overcame.","options":["Say you faced no challenges","Use STAR method: Situation, Task, Action, Result","Blame others","Keep it vague"],"answer":"Use STAR method: Situation, Task, Action, Result","explanation":"STAR method gives structured, compelling answers to behavioral questions."},
{"id":20,"question":"What is Big O notation?","options":["A programming language","Mathematical notation for algorithm performance as input grows","A database term","A design pattern"],"answer":"Mathematical notation for algorithm performance as input grows","explanation":"O(1)=constant, O(log n)=logarithmic, O(n)=linear, O(n²)=quadratic."},
{"id":21,"question":"What is a stack overflow error?","options":["Website error","Occurs when call stack exceeds memory limit, usually due to infinite recursion","Memory leak","Database error"],"answer":"Occurs when call stack exceeds memory limit, usually due to infinite recursion","explanation":"Each recursive call uses stack frame space. Too many nested calls cause StackOverflowError."},
{"id":22,"question":"What is the difference between final, finally, and finalize?","options":["All same","final=keyword, finally=exception block, finalize=GC method","Only syntax differs","All are keywords"],"answer":"final=keyword, finally=exception block, finalize=GC method","explanation":"final prevents modification/inheritance, finally always runs after try-catch, finalize is called by GC."},
{"id":23,"question":"Do you prefer working alone or in a team?","options":["Always alone","I am comfortable with both; I collaborate effectively in teams while being self-sufficient individually","Always in team","Depends on mood"],"answer":"I am comfortable with both; I collaborate effectively in teams while being self-sufficient individually","explanation":"Show adaptability and collaboration skills while highlighting independence."},
{"id":24,"question":"What is MVC architecture?","options":["A database type","Model-View-Controller: separates data, UI, and control logic","A testing framework","A cloud service"],"answer":"Model-View-Controller: separates data, UI, and control logic","explanation":"MVC improves maintainability by keeping concerns separated across three components."},
{"id":25,"question":"What is the difference between checked and unchecked exceptions?","options":["No difference","Checked exceptions are caught at compile time; unchecked at runtime","Unchecked are more serious","Checked are from user errors"],"answer":"Checked exceptions are caught at compile time; unchecked at runtime","explanation":"Checked: IOException, SQLException. Unchecked: NullPointerException, ArrayIndexOutOfBoundsException."},
{"id":26,"question":"What is Agile methodology?","options":["Waterfall development","Iterative development framework focusing on collaboration, flexibility, and customer feedback","A testing tool","A programming language"],"answer":"Iterative development framework focusing on collaboration, flexibility, and customer feedback","explanation":"Agile uses sprints, standups, retrospectives, and continuous delivery to adapt to changing requirements."},
{"id":27,"question":"What is Git and why is it used?","options":["A database","Distributed version control system to track code changes and collaborate","An IDE","A deployment tool"],"answer":"Distributed version control system to track code changes and collaborate","explanation":"Git allows branching, merging, rollbacks, and collaboration. Key commands: commit, push, pull, branch."},
{"id":28,"question":"How do you stay updated with technology?","options":["I do not follow trends","Read tech blogs, take online courses, build side projects, and follow open source projects","Watch movies","Ask colleagues only"],"answer":"Read tech blogs, take online courses, build side projects, and follow open source projects","explanation":"Demonstrates genuine passion for learning and continuous improvement."},
{"id":29,"question":"What is the difference between synchronous and asynchronous programming?","options":["Same","Synchronous blocks execution; asynchronous allows continuation while waiting for tasks","Async is slower","Sync is more modern"],"answer":"Synchronous blocks execution; asynchronous allows continuation while waiting for tasks","explanation":"Async (Promises, async/await) prevents blocking UI/server while waiting for I/O operations."},
{"id":30,"question":"What makes a good software engineer?","options":["Just coding skills","Combination of technical skills, problem-solving, communication, and continuous learning","Only algorithms knowledge","Knowing many languages"],"answer":"Combination of technical skills, problem-solving, communication, and continuous learning","explanation":"Top engineers combine technical depth with clarity of thinking, teamwork, and lifelong learning."}
]');

-- ============================================================
-- 3. DOMAIN CORE - Java, DBMS, OS, CN (30 Questions)
-- ============================================================
INSERT INTO mock_tests (title, type, duration_minutes, category, questions) VALUES 
('Domain Core — Java, OS, DBMS, Networks (30Q)', 'TECHNICAL', 50, 'DOMAIN',
'[
{"id":1,"question":"Which of the following is NOT a feature of Java?","options":["Platform independence","Pointers","Object-oriented","Multithreading"],"answer":"Pointers","explanation":"Java does not support explicit pointer manipulation, unlike C/C++."},
{"id":2,"question":"Which Java keyword prevents method overriding?","options":["static","private","final","abstract"],"answer":"final","explanation":"A final method cannot be overridden in subclasses."},
{"id":3,"question":"What does the volatile keyword do in Java?","options":["Makes variable constant","Ensures variable is read from main memory, not thread cache","Marks deprecated code","Enables serialization"],"answer":"Ensures variable is read from main memory, not thread cache","explanation":"volatile ensures visibility of changes across threads without synchronization."},
{"id":4,"question":"Which collection allows null keys and values?","options":["Hashtable","TreeMap","HashMap","ConcurrentHashMap"],"answer":"HashMap","explanation":"HashMap allows one null key and multiple null values. Hashtable does not allow nulls."},
{"id":5,"question":"What is the purpose of the synchronized keyword?","options":["Speed up execution","Allow only one thread at a time to access a block","Create new threads","Mark deprecated methods"],"answer":"Allow only one thread at a time to access a block","explanation":"synchronized enables mutual exclusion to prevent race conditions in multithreaded programs."},
{"id":6,"question":"In Java, String is:","options":["Primitive type","Mutable object","Immutable object","Interface"],"answer":"Immutable object","explanation":"String objects cannot be changed once created. Operations return new String objects."},
{"id":7,"question":"What is the output of: System.out.println(10/3)?","options":["3.33","3","4","Error"],"answer":"3","explanation":"Integer division in Java truncates the decimal. 10/3 = 3 (not 3.33)."},
{"id":8,"question":"Which sorting algorithm has best worst-case time complexity?","options":["Quick Sort","Bubble Sort","Merge Sort","Selection Sort"],"answer":"Merge Sort","explanation":"Merge Sort guarantees O(n log n) in all cases; Quick Sort can degrade to O(n²)."},
{"id":9,"question":"What does SQL HAVING clause do?","options":["Filters rows before grouping","Filters groups after GROUP BY","Joins tables","Sorts results"],"answer":"Filters groups after GROUP BY","explanation":"HAVING filters aggregated groups, while WHERE filters individual rows before grouping."},
{"id":10,"question":"What is BCNF in database normalization?","options":["1st Normal Form","Boyce-Codd Normal Form: stronger version of 3NF","Binary Coded Normal Form","Base Column Normal Form"],"answer":"Boyce-Codd Normal Form: stronger version of 3NF","explanation":"BCNF requires that for every functional dependency X→Y, X must be a superkey."},
{"id":11,"question":"What is a deadlock prevention technique?","options":["Circular wait only","Resource ordering, banker algorithm, or preemption","Ignoring it","Rebooting system"],"answer":"Resource ordering, banker algorithm, or preemption","explanation":"Deadlock prevention breaks one of the four conditions (Circular Wait, Hold & Wait, etc.)."},
{"id":12,"question":"What does CPU scheduling algorithm Round Robin use?","options":["Priority queue","Fixed time quantum for each process in circular order","Shortest job first","FIFO only"],"answer":"Fixed time quantum for each process in circular order","explanation":"Round Robin gives each process a time slice (quantum) and cycles through all processes."},
{"id":13,"question":"What is paging in OS memory management?","options":["Swapping processes","Dividing memory into fixed-size frames and process into pages","Defragmenting disk","Loading programs"],"answer":"Dividing memory into fixed-size frames and process into pages","explanation":"Paging eliminates external fragmentation by mapping logical pages to physical frames."},
{"id":14,"question":"What layer does IP operate at in OSI model?","options":["Physical","Data Link","Network","Transport"],"answer":"Network","explanation":"IP (Internet Protocol) operates at Layer 3 (Network Layer) for logical addressing and routing."},
{"id":15,"question":"What is the difference between TCP and UDP?","options":["Same protocol","TCP is reliable, connection-oriented; UDP is faster, connectionless","UDP is more secure","TCP is faster"],"answer":"TCP is reliable, connection-oriented; UDP is faster, connectionless","explanation":"TCP guarantees delivery via handshakes/ACKs. UDP is used for real-time apps (video, DNS)."},
{"id":16,"question":"What does a DNS server do?","options":["Encrypts traffic","Translates domain names to IP addresses","Manages emails","Hosts websites"],"answer":"Translates domain names to IP addresses","explanation":"DNS (Domain Name System) resolves human-readable names (google.com) to IP addresses."},
{"id":17,"question":"What is an index in a database?","options":["A backup","Data structure that improves speed of data retrieval","A constraint","A stored procedure"],"answer":"Data structure that improves speed of data retrieval","explanation":"Indexes (B-Tree, Hash) allow O(log n) lookups instead of full table scans O(n)."},
{"id":18,"question":"What is the difference between INNER JOIN and LEFT JOIN?","options":["Same","INNER JOIN returns matching rows only; LEFT JOIN returns all left rows + matches","LEFT JOIN is faster","INNER JOIN returns all rows"],"answer":"INNER JOIN returns matching rows only; LEFT JOIN returns all left rows + matches","explanation":"LEFT JOIN includes all rows from the left table, with NULLs for non-matching right rows."},
{"id":19,"question":"Which data structure is used for implementing recursion?","options":["Queue","Stack","Heap","Array"],"answer":"Stack","explanation":"Each recursive call is pushed onto the call stack. Stack frames are popped on return."},
{"id":20,"question":"What is thrashing in OS?","options":["Fast process execution","High paging activity causing more time swapping than executing","Hard disk failure","CPU overheating"],"answer":"High paging activity causing more time swapping than executing","explanation":"Thrashing occurs when working set exceeds available memory, causing constant page faults."},
{"id":21,"question":"What is a semaphore?","options":["A network protocol","Synchronization primitive using a counter to control access to shared resources","A Java keyword","A data structure"],"answer":"Synchronization primitive using a counter to control access to shared resources","explanation":"Binary semaphore = mutex. Counting semaphore controls access by N processes simultaneously."},
{"id":22,"question":"What is ACID in database transactions?","options":["A programming language","Atomicity, Consistency, Isolation, Durability — transaction properties","A cloud service","An encryption standard"],"answer":"Atomicity, Consistency, Isolation, Durability — transaction properties","explanation":"ACID ensures reliable database transactions that survive errors and system failures."},
{"id":23,"question":"What is the three-way handshake in TCP?","options":["UDP connection setup","SYN → SYN-ACK → ACK to establish TCP connection","DNS resolution","HTTP request cycle"],"answer":"SYN → SYN-ACK → ACK to establish TCP connection","explanation":"Client sends SYN, server replies SYN-ACK, client sends ACK to establish connection."},
{"id":24,"question":"What is method overloading?","options":["Same method, different class","Multiple methods with same name but different parameters in same class","Overriding parent method","Abstract method implementation"],"answer":"Multiple methods with same name but different parameters in same class","explanation":"Overloading is compile-time polymorphism resolved by parameter types/count."},
{"id":25,"question":"What is a primary key constraint?","options":["Optional column","Ensures uniqueness and non-null values for a column identifying each row","Allows duplicates","Foreign key reference"],"answer":"Ensures uniqueness and non-null values for a column identifying each row","explanation":"Primary key = UNIQUE + NOT NULL. Each table can have only one primary key."},
{"id":26,"question":"What is virtual memory?","options":["RAM only","Technique using disk space to extend apparent available RAM","GPU memory","Cache memory"],"answer":"Technique using disk space to extend apparent available RAM","explanation":"OS maps virtual addresses to physical memory, swapping pages to disk when RAM is full."},
{"id":27,"question":"What is the difference between stack and heap memory in Java?","options":["Same memory","Stack stores method frames/local variables; Heap stores objects","Heap is faster","Stack is larger"],"answer":"Stack stores method frames/local variables; Heap stores objects","explanation":"Stack is thread-local and auto-managed. Heap is shared and managed by Garbage Collector."},
{"id":28,"question":"What is a subnet mask?","options":["Firewall rule","32-bit number that divides IP address into network and host portions","MAC address","DNS record"],"answer":"32-bit number that divides IP address into network and host portions","explanation":"192.168.1.0/24 means 24 bits for network, 8 bits for hosts (254 usable IPs)."},
{"id":29,"question":"What is the difference between HashMap and TreeMap?","options":["Same","HashMap is O(1) unordered; TreeMap is O(log n) sorted by keys","TreeMap is faster","HashMap uses trees"],"answer":"HashMap is O(1) unordered; TreeMap is O(log n) sorted by keys","explanation":"TreeMap uses Red-Black Tree, maintaining sorted order at cost of O(log n) operations."},
{"id":30,"question":"What is a NullPointerException?","options":["Compilation error","Runtime exception when accessing a method/field on a null object reference","Syntax error","Memory leak"],"answer":"Runtime exception when accessing a method/field on a null object reference","explanation":"Occurs when you call methods/access fields on a variable that points to null instead of an object."}
]');
