-- V10: 30 questions each for COMPETITIVE, INTERVIEW, DOMAIN categories
-- Each test gets questions inserted as JSON array

-- Update COMPETITIVE test with 30 questions
UPDATE mock_tests 
SET duration_minutes = 45, 
    questions = '[
{"id":"c1","question":"A train 150m long passes a pole in 15 seconds. What is its speed in km/h?","options":["36 km/h","40 km/h","54 km/h","60 km/h"],"answer":"36 km/h","explanation":"Speed = 150/15 = 10 m/s = 36 km/h"},
{"id":"c2","question":"If A can do a work in 12 days and B in 18 days, in how many days can they do it together?","options":["7.2 days","6 days","7 days","8 days"],"answer":"7.2 days","explanation":"Combined rate = 1/12+1/18 = 5/36, so days = 36/5 = 7.2"},
{"id":"c3","question":"What is the LCM of 12, 18 and 24?","options":["48","72","36","96"],"answer":"72","explanation":"LCM(12,18,24)=72"},
{"id":"c4","question":"A shopkeeper marks goods 25% above cost price and gives 10% discount. Find profit%.","options":["12.5%","15%","10%","17.5%"],"answer":"12.5%","explanation":"SP = 1.25*0.9 = 1.125 CP, profit = 12.5%"},
{"id":"c5","question":"In how many ways can 5 books be arranged on a shelf?","options":["60","120","24","240"],"answer":"120","explanation":"5! = 120"},
{"id":"c6","question":"If 6 men can do a piece of work in 12 days, how many men are needed to do it in 9 days?","options":["8","9","10","7"],"answer":"8","explanation":"6*12 = x*9, x=8"},
{"id":"c7","question":"Find the compound interest on Rs.5000 at 10% p.a. for 2 years.","options":["Rs.1000","Rs.1050","Rs.1100","Rs.500"],"answer":"Rs.1050","explanation":"CI = 5000*(1.1^2 - 1) = 5000*0.21 = 1050"},
{"id":"c8","question":"The ratio of ages of A and B is 3:5. After 6 years ratio becomes 3:4. Find A''s present age.","options":["6","9","12","15"],"answer":"6","explanation":"3x+6 / 5x+6 = 3/4, solve x=2, A=6"},
{"id":"c9","question":"A number when divided by 5 gives remainder 3. What is the remainder when divided by 10?","options":["3 or 8","3","8","5"],"answer":"3 or 8","explanation":"Numbers: 3,8,13,18... div by 10 gives 3 or 8"},
{"id":"c10","question":"If PAPER is coded as SDSHU, how is PENCIL coded?","options":["SHQFLO","SHQFLN","SGPFLO","RHPFLN"],"answer":"SHQFLO","explanation":"Each letter shifted by +3 in alphabet"},
{"id":"c11","question":"What comes next: 2, 6, 12, 20, 30, ?","options":["40","42","44","48"],"answer":"42","explanation":"Differences: 4,6,8,10,12 → next = 30+12=42"},
{"id":"c12","question":"A is taller than B but shorter than C. D is shorter than A but taller than B. Who is shortest?","options":["B","D","A","C"],"answer":"B","explanation":"C>A>D>B, so B is shortest"},
{"id":"c13","question":"If 2x+3y=12 and x-y=1, find x.","options":["3","4","2","5"],"answer":"3","explanation":"From x=y+1: 2(y+1)+3y=12 → 5y=10 → y=2, x=3"},
{"id":"c14","question":"A pipe fills tank in 4 hours, another empties in 12 hours. Together, fill time?","options":["6 hours","8 hours","10 hours","12 hours"],"answer":"6 hours","explanation":"Net rate = 1/4 - 1/12 = 1/6, time = 6 hrs"},
{"id":"c15","question":"Select the odd one out: 2, 3, 5, 7, 9, 11","options":["9","3","5","11"],"answer":"9","explanation":"9 = 3x3 is not prime, all others are prime"},
{"id":"c16","question":"Simple interest on Rs.2000 at 5% for 3 years is?","options":["Rs.300","Rs.250","Rs.350","Rs.400"],"answer":"Rs.300","explanation":"SI = 2000*5*3/100 = 300"},
{"id":"c17","question":"A 300m train crosses a 200m bridge in 50 seconds. Speed in m/s?","options":["10","8","12","15"],"answer":"10","explanation":"Speed = (300+200)/50 = 10 m/s"},
{"id":"c18","question":"A is the father of B. B is the sister of C. C is the mother of D. How is A related to D?","options":["Grandfather","Father","Uncle","Grandmother"],"answer":"Grandfather","explanation":"A→B→C→D: A is grandfather of D"},
{"id":"c19","question":"Find the missing: 1, 4, 9, 16, 25, ?","options":["36","49","35","38"],"answer":"36","explanation":"Perfect squares: 1,4,9,16,25,36"},
{"id":"c20","question":"In a class, 60% passed in Math and 70% in Science. 40% passed both. How many failed both?","options":["10%","20%","30%","15%"],"answer":"10%","explanation":"Union = 60+70-40 = 90%, failed both = 10%"},
{"id":"c21","question":"If P=16, R=18, T=20, then Q=?","options":["17","15","19","16"],"answer":"17","explanation":"P=16(position), Q=17, R=18 pattern"},
{"id":"c22","question":"Average of 5 numbers is 10. If one number is removed, average becomes 8. Removed number?","options":["18","16","20","14"],"answer":"18","explanation":"Sum=50, new sum=32, removed=50-32=18"},
{"id":"c23","question":"Which is the largest 4-digit number divisible by 12?","options":["9996","9984","9988","9992"],"answer":"9996","explanation":"9996/12=833 exactly"},
{"id":"c24","question":"A boy walks 5km East then 12km North. Distance from start?","options":["13 km","17 km","15 km","14 km"],"answer":"13 km","explanation":"sqrt(5^2+12^2)=sqrt(169)=13"},
{"id":"c25","question":"Profit is 20% of selling price. Find profit % on cost price.","options":["25%","20%","15%","30%"],"answer":"25%","explanation":"If SP=100, profit=20, CP=80, profit%=20/80*100=25%"},
{"id":"c26","question":"How many prime numbers are between 1 and 30?","options":["10","11","9","12"],"answer":"10","explanation":"2,3,5,7,11,13,17,19,23,29 = 10 primes"},
{"id":"c27","question":"A ball is thrown up with velocity 20 m/s. Maximum height (g=10)?","options":["20 m","10 m","40 m","30 m"],"answer":"20 m","explanation":"h = v^2/2g = 400/20 = 20m"},
{"id":"c28","question":"In a group of 80, ratio of men to women is 3:1. How many women?","options":["20","25","30","15"],"answer":"20","explanation":"Women = 80*(1/4) = 20"},
{"id":"c29","question":"If log(2)=0.301, find log(8).","options":["0.903","0.602","1.204","0.9"],"answer":"0.903","explanation":"log(8)=log(2^3)=3*0.301=0.903"},
{"id":"c30","question":"Which statement about recursion is TRUE?","options":["Must have base case","Always uses loop","Cannot return values","Uses goto statement"],"answer":"Must have base case","explanation":"Every recursive function needs a base case to terminate"}
]'
WHERE category = 'COMPETITIVE'
LIMIT 1;

-- Update INTERVIEW test with 30 questions
UPDATE mock_tests 
SET duration_minutes = 50, 
    questions = '[
{"id":"i1","question":"What are the four pillars of OOP?","options":["Abstraction, Encapsulation, Inheritance, Polymorphism","Classes, Objects, Methods, Variables","Compile, Run, Debug, Deploy","Functions, Loops, Arrays, Pointers"],"answer":"Abstraction, Encapsulation, Inheritance, Polymorphism","explanation":"The 4 pillars of OOP are Abstraction, Encapsulation, Inheritance, and Polymorphism."},
{"id":"i2","question":"What is the difference between process and thread?","options":["Process has own memory space; thread shares process memory","Thread has own memory; process shares","Both are identical","Process is faster than thread"],"answer":"Process has own memory space; thread shares process memory","explanation":"A process is an independent execution unit with its own memory. Threads within a process share the same memory space."},
{"id":"i3","question":"What does ACID stand for in databases?","options":["Atomicity, Consistency, Isolation, Durability","Access, Control, Index, Data","Array, Class, Interface, Data","Authentication, Cipher, Input, Data"],"answer":"Atomicity, Consistency, Isolation, Durability","explanation":"ACID guarantees database transactions are processed reliably."},
{"id":"i4","question":"What is the time complexity of binary search?","options":["O(log n)","O(n)","O(n log n)","O(1)"],"answer":"O(log n)","explanation":"Binary search halves the search space each step, giving O(log n)."},
{"id":"i5","question":"What is deadlock in OS?","options":["A situation where processes wait for each other indefinitely","When CPU usage is 100%","A memory overflow error","When a process terminates unexpectedly"],"answer":"A situation where processes wait for each other indefinitely","explanation":"Deadlock occurs when two or more processes wait for resources held by each other, causing a circular wait."},
{"id":"i6","question":"What is normalization in databases?","options":["Process of organizing data to reduce redundancy","Increasing database size","Adding indexes to tables","Encrypting database fields"],"answer":"Process of organizing data to reduce redundancy","explanation":"Normalization organizes tables to minimize data redundancy and dependency."},
{"id":"i7","question":"What is the difference between TCP and UDP?","options":["TCP is reliable and connection-oriented; UDP is faster but unreliable","UDP is reliable; TCP is not","Both are identical","TCP is for video streaming only"],"answer":"TCP is reliable and connection-oriented; UDP is faster but unreliable","explanation":"TCP guarantees delivery via handshake; UDP sends packets without acknowledgment."},
{"id":"i8","question":"What is a foreign key?","options":["A key that references a primary key of another table","A key used for encryption","A unique identifier within the same table","A composite key with multiple columns"],"answer":"A key that references a primary key of another table","explanation":"Foreign keys establish referential integrity between tables."},
{"id":"i9","question":"What is polymorphism?","options":["Ability of an object to take many forms","Hiding internal implementation","Inheriting properties from parent","Breaking a problem into smaller parts"],"answer":"Ability of an object to take many forms","explanation":"Polymorphism allows methods to behave differently based on the object type."},
{"id":"i10","question":"What is virtual memory?","options":["Memory management extending RAM using disk space","Memory inside the CPU","Cache memory","ROM memory"],"answer":"Memory management extending RAM using disk space","explanation":"Virtual memory uses disk space to extend the available memory for processes."},
{"id":"i11","question":"What is a REST API?","options":["Stateless HTTP-based interface using standard methods","A type of database","A programming language","A security protocol"],"answer":"Stateless HTTP-based interface using standard methods","explanation":"REST uses HTTP methods (GET,POST,PUT,DELETE) and is stateless."},
{"id":"i12","question":"What is the purpose of the JVM?","options":["Execute Java bytecode on any platform","Compile Java source code","Manage Java database connections","Provide a GUI for Java apps"],"answer":"Execute Java bytecode on any platform","explanation":"JVM provides platform independence by executing compiled bytecode."},
{"id":"i13","question":"What is an abstract class?","options":["A class that cannot be instantiated and may have abstract methods","A class with only static methods","A final class","A class without constructors"],"answer":"A class that cannot be instantiated and may have abstract methods","explanation":"Abstract classes serve as templates and can contain both abstract and concrete methods."},
{"id":"i14","question":"What is the difference between == and .equals() in Java?","options":["== compares references; .equals() compares values","== compares values; .equals() compares references","Both compare values","Both compare references"],"answer":"== compares references; .equals() compares values","explanation":"== checks if two references point to the same object; .equals() checks value equality."},
{"id":"i15","question":"What is encapsulation?","options":["Bundling data and methods, restricting direct access","Inheriting from a parent class","Creating multiple objects from a class","Running multiple threads simultaneously"],"answer":"Bundling data and methods, restricting direct access","explanation":"Encapsulation hides internal state and exposes behavior through public methods."},
{"id":"i16","question":"What is a stack overflow?","options":["When the call stack exceeds its limit due to infinite recursion","When RAM is full","When disk space is exhausted","A popular developer website"],"answer":"When the call stack exceeds its limit due to infinite recursion","explanation":"Each function call adds a frame to the stack; infinite recursion causes overflow."},
{"id":"i17","question":"What is the CAP theorem?","options":["A distributed system can only guarantee 2 of: Consistency, Availability, Partition Tolerance","A security model","A sorting algorithm","A database indexing strategy"],"answer":"A distributed system can only guarantee 2 of: Consistency, Availability, Partition Tolerance","explanation":"CAP theorem is fundamental to designing distributed databases."},
{"id":"i18","question":"What is garbage collection in Java?","options":["Automatic memory management that frees unused objects","Manual deletion of objects","Compiling unused code","Logging application errors"],"answer":"Automatic memory management that frees unused objects","explanation":"Java''s GC automatically identifies and removes objects no longer referenced."},
{"id":"i19","question":"What is an index in SQL?","options":["A data structure that speeds up data retrieval","A column that stores numbers only","A trigger that fires on insert","A constraint type"],"answer":"A data structure that speeds up data retrieval","explanation":"Indexes allow the DB engine to find rows faster without scanning the entire table."},
{"id":"i20","question":"What is the difference between GET and POST HTTP methods?","options":["GET retrieves data (idempotent); POST submits data (non-idempotent)","POST retrieves data; GET submits data","Both are identical","GET is faster than POST in all cases"],"answer":"GET retrieves data (idempotent); POST submits data (non-idempotent)","explanation":"GET is safe and idempotent; POST creates/updates resources."},
{"id":"i21","question":"What is a semaphore in OS?","options":["A synchronization primitive controlling access to shared resources","A type of memory","A file system component","A CPU scheduling algorithm"],"answer":"A synchronization primitive controlling access to shared resources","explanation":"Semaphores manage concurrent access to shared resources using wait/signal operations."},
{"id":"i22","question":"What is coupling in software design?","options":["Degree of dependency between modules","Number of classes in a module","Lines of code per function","Test coverage percentage"],"answer":"Degree of dependency between modules","explanation":"Low coupling is preferred for maintainability; high coupling makes changes ripple across modules."},
{"id":"i23","question":"What is the difference between HashMap and Hashtable in Java?","options":["HashMap is unsynchronized and allows null; Hashtable is synchronized","Hashtable allows null; HashMap does not","Both are identical","HashMap is always faster"],"answer":"HashMap is unsynchronized and allows null; Hashtable is synchronized","explanation":"HashMap is preferred for single-threaded use; Hashtable for legacy thread-safe code."},
{"id":"i24","question":"What is a design pattern?","options":["A reusable solution to a common software design problem","A coding style guide","A database schema template","A type of algorithm"],"answer":"A reusable solution to a common software design problem","explanation":"Design patterns (GoF) provide proven solutions to recurring design challenges."},
{"id":"i25","question":"What is the Singleton pattern?","options":["Ensures only one instance of a class exists","Creates multiple objects with shared state","Allows objects to be cloned","Separates interface from implementation"],"answer":"Ensures only one instance of a class exists","explanation":"Singleton restricts instantiation to one object, providing a global access point."},
{"id":"i26","question":"What is paging in OS?","options":["Dividing process memory into fixed-size pages mapped to frames","Sorting processes by priority","Allocating memory contiguously","A file system journaling technique"],"answer":"Dividing process memory into fixed-size pages mapped to frames","explanation":"Paging eliminates external fragmentation by using fixed-size memory blocks."},
{"id":"i27","question":"What is the difference between SQL JOIN types: INNER vs LEFT?","options":["INNER returns matching rows only; LEFT returns all left + matching right","LEFT returns matching only; INNER returns all","Both return same results","INNER returns all rows from both tables"],"answer":"INNER returns matching rows only; LEFT returns all left + matching right","explanation":"INNER JOIN: intersection; LEFT JOIN: all left table rows + matched right rows."},
{"id":"i28","question":"What is method overloading?","options":["Same method name with different parameters in the same class","Overriding a parent method in child class","Creating abstract methods","Running methods in parallel"],"answer":"Same method name with different parameters in the same class","explanation":"Overloading is compile-time polymorphism; different signatures, same class."},
{"id":"i29","question":"What is the Observer design pattern?","options":["An object notifies multiple dependents when its state changes","A pattern for creating objects","A database access pattern","A security authentication pattern"],"answer":"An object notifies multiple dependents when its state changes","explanation":"Observer pattern implements publish-subscribe for event-driven programming."},
{"id":"i30","question":"What is Big O notation?","options":["Describes worst-case time/space complexity of an algorithm","Describes best-case complexity only","A type of sorting algorithm","A database query optimizer"],"answer":"Describes worst-case time/space complexity of an algorithm","explanation":"Big O notation gives an upper bound on how an algorithm scales with input size."}
]'
WHERE category = 'INTERVIEW'
LIMIT 1;

-- Update DOMAIN test with 30 questions
UPDATE mock_tests 
SET duration_minutes = 50, 
    questions = '[
{"id":"d1","question":"Which Java collection allows null keys and values?","options":["HashMap","Hashtable","TreeMap","LinkedHashMap"],"answer":"HashMap","explanation":"HashMap allows one null key and multiple null values; Hashtable does not allow null."},
{"id":"d2","question":"In React, what does useState return?","options":["A state variable and a setter function","Only the state value","Only the setter function","A ref object"],"answer":"A state variable and a setter function","explanation":"useState returns [currentState, setterFunction] as a tuple."},
{"id":"d3","question":"Which HTTP status code means ''Not Found''?","options":["404","200","500","301"],"answer":"404","explanation":"404 Not Found is returned when the requested resource does not exist."},
{"id":"d4","question":"What is a microservice architecture?","options":["Application built as small independent services communicating via APIs","A single large application","A database architecture","A frontend framework"],"answer":"Application built as small independent services communicating via APIs","explanation":"Microservices decompose an app into independently deployable services."},
{"id":"d5","question":"Which SQL clause filters after grouping?","options":["HAVING","WHERE","GROUP BY","ORDER BY"],"answer":"HAVING","explanation":"HAVING filters groups after GROUP BY; WHERE filters rows before grouping."},
{"id":"d6","question":"What does Docker do?","options":["Containerizes applications with their dependencies","Provides version control","Manages databases","Monitors server performance"],"answer":"Containerizes applications with their dependencies","explanation":"Docker packages apps and dependencies into portable containers."},
{"id":"d7","question":"What is the Virtual DOM in React?","options":["In-memory DOM representation React uses to optimize updates","The actual browser DOM","A virtual machine for running React","A state management library"],"answer":"In-memory DOM representation React uses to optimize updates","explanation":"React diffs the virtual DOM with the real DOM and applies minimal updates."},
{"id":"d8","question":"What is Spring Boot auto-configuration?","options":["Automatically configures Spring app based on classpath dependencies","A build tool","A testing framework","A deployment strategy"],"answer":"Automatically configures Spring app based on classpath dependencies","explanation":"Spring Boot scans classpath and configures beans automatically, reducing boilerplate."},
{"id":"d9","question":"What is the purpose of @RestController in Spring?","options":["Combines @Controller and @ResponseBody for REST endpoints","Marks a class as a database repository","Schedules background tasks","Configures security"],"answer":"Combines @Controller and @ResponseBody for REST endpoints","explanation":"@RestController makes every method return JSON/XML directly without @ResponseBody."},
{"id":"d10","question":"What is a Lambda expression in Java?","options":["An anonymous function implementing a functional interface","A class declaration","A loop construct","A type of exception"],"answer":"An anonymous function implementing a functional interface","explanation":"Lambdas enable functional programming in Java 8+, implementing single-method interfaces."},
{"id":"d11","question":"In SQL, what does INDEX do?","options":["Speeds up SELECT queries by creating a lookup structure","Inserts records faster","Joins multiple tables","Creates a backup"],"answer":"Speeds up SELECT queries by creating a lookup structure","explanation":"Indexes trade write performance for faster read lookups."},
{"id":"d12","question":"What is CORS?","options":["Browser security mechanism restricting cross-origin HTTP requests","A Java framework","A CSS preprocessor","An API authentication method"],"answer":"Browser security mechanism restricting cross-origin HTTP requests","explanation":"CORS controls which origins can access resources on a server."},
{"id":"d13","question":"Which React hook replaces componentDidMount?","options":["useEffect","useState","useCallback","useReducer"],"answer":"useEffect","explanation":"useEffect with an empty dependency array runs once after mount, like componentDidMount."},
{"id":"d14","question":"What is JWT?","options":["A compact token format for securely transmitting claims between parties","A JavaScript testing tool","A Java build framework","A type of SQL query"],"answer":"A compact token format for securely transmitting claims between parties","explanation":"JWT consists of header.payload.signature and is used for stateless authentication."},
{"id":"d15","question":"What is Redis primarily used for?","options":["In-memory caching and key-value storage","SQL database management","Frontend state management","Container orchestration"],"answer":"In-memory caching and key-value storage","explanation":"Redis is an in-memory data structure store used for caching, pub/sub, and sessions."},
{"id":"d16","question":"What is the difference between ArrayList and LinkedList?","options":["ArrayList uses dynamic array (O(1) access); LinkedList uses nodes (O(1) insert)","LinkedList is faster for random access","Both have identical performance","ArrayList is always preferred"],"answer":"ArrayList uses dynamic array (O(1) access); LinkedList uses nodes (O(1) insert)","explanation":"ArrayList is better for random access; LinkedList for frequent insertions/deletions."},
{"id":"d17","question":"What does async/await do in JavaScript?","options":["Makes asynchronous code look synchronous using Promises","Creates multiple threads","Synchronously blocks execution","Handles CSS animations"],"answer":"Makes asynchronous code look synchronous using Promises","explanation":"async/await is syntactic sugar over Promises, making async code readable."},
{"id":"d18","question":"What is Kubernetes?","options":["Container orchestration platform for automating deployment and scaling","A version control system","A monitoring tool","A CI/CD pipeline tool"],"answer":"Container orchestration platform for automating deployment and scaling","explanation":"Kubernetes manages containerized applications across clusters of hosts."},
{"id":"d19","question":"What is a primary key in SQL?","options":["A unique, non-null identifier for each row in a table","A key used for joins","A foreign key reference","An optional column identifier"],"answer":"A unique, non-null identifier for each row in a table","explanation":"Primary keys must be unique and not null, uniquely identifying each row."},
{"id":"d20","question":"What does the @Transactional annotation do in Spring?","options":["Wraps a method in a database transaction that rolls back on exception","Marks a REST endpoint","Enables caching","Configures security"],"answer":"Wraps a method in a database transaction that rolls back on exception","explanation":"@Transactional ensures all database operations in the method succeed or all rollback."},
{"id":"d21","question":"What is the difference between props and state in React?","options":["Props are passed from parent (read-only); state is managed within component","State is passed from parent; props are internal","Both are identical","Props can be modified directly"],"answer":"Props are passed from parent (read-only); state is managed within component","explanation":"Props are immutable inputs; state is mutable internal component data."},
{"id":"d22","question":"What is an ORM?","options":["Maps database tables to objects, eliminating raw SQL","A frontend framework","A REST API tool","A server runtime"],"answer":"Maps database tables to objects, eliminating raw SQL","explanation":"ORMs like Hibernate/JPA let you work with objects instead of writing SQL."},
{"id":"d23","question":"What is the Event Loop in Node.js?","options":["Mechanism enabling non-blocking I/O on a single thread","A type of for loop","A database connection pool","A load balancing algorithm"],"answer":"Mechanism enabling non-blocking I/O on a single thread","explanation":"Node.js event loop processes async callbacks in a single thread using phases."},
{"id":"d24","question":"What is a closure in JavaScript?","options":["A function that remembers its outer scope even after the outer function returns","A way to close HTTP connections","A CSS layout technique","A type of Promise"],"answer":"A function that remembers its outer scope even after the outer function returns","explanation":"Closures enable data encapsulation and module patterns in JavaScript."},
{"id":"d25","question":"What is dependency injection in Spring?","options":["Spring provides dependencies to objects rather than objects creating them","Objects creating their own dependencies","A testing pattern","A database migration technique"],"answer":"Spring provides dependencies to objects rather than objects creating them","explanation":"DI decouples components, making them easier to test and maintain."},
{"id":"d26","question":"What is connection pooling?","options":["Reusing existing database connections instead of creating new ones","Joining multiple databases","A network load balancing technique","A type of SQL query"],"answer":"Reusing existing database connections instead of creating new ones","explanation":"Connection pools improve performance by reusing connections across requests."},
{"id":"d27","question":"What is the purpose of useCallback in React?","options":["Memoizes a callback function to prevent unnecessary re-renders","Fetches data from APIs","Manages global state","Handles routing"],"answer":"Memoizes a callback function to prevent unnecessary re-renders","explanation":"useCallback returns a memoized version of the callback that only changes if dependencies change."},
{"id":"d28","question":"What is a deadlock in database transactions?","options":["Two transactions waiting for each other''s locked resources indefinitely","A slow query timeout","A failed migration","An index conflict"],"answer":"Two transactions waiting for each other''s locked resources indefinitely","explanation":"Database deadlocks occur when transactions hold locks and wait for locks held by each other."},
{"id":"d29","question":"What is the difference between 3NF and BCNF normalization?","options":["BCNF is stricter; every determinant must be a candidate key","3NF is stricter than BCNF","Both are identical","BCNF allows more redundancy"],"answer":"BCNF is stricter; every determinant must be a candidate key","explanation":"BCNF (Boyce-Codd) is a stronger form of 3NF with stricter functional dependency rules."},
{"id":"d30","question":"What is load balancing?","options":["Distributing incoming traffic across multiple servers to prevent overload","Compressing files for faster transfer","Caching frequently accessed data","Encrypting network traffic"],"answer":"Distributing incoming traffic across multiple servers to prevent overload","explanation":"Load balancers improve availability and scalability by distributing requests evenly."}
]'
WHERE category = 'DOMAIN'
LIMIT 1;
